import type { GenerationTask } from "./types";

const now = Date.now();

export function createSeedTasks(): GenerationTask[] {
  return [
    {
      id: "task-1",
      type: "image",
      prompt: "Неоновый киберпанк-город под дождём, вид сверху",
      model: "Midjourney v6",
      status: "running",
      progress: 64,
      credits: 80,
      etaSeconds: 30,
      createdAt: now - 120_000,
      updatedAt: now - 30_000,
    },
    {
      id: "task-2",
      type: "video",
      prompt: "Дрон-облёт горного озера на рассвете",
      model: "Kling 3.0",
      status: "running",
      progress: 28,
      credits: 150,
      etaSeconds: 120,
      createdAt: now - 180_000,
      updatedAt: now - 45_000,
    },
    {
      id: "task-3",
      type: "text",
      prompt: "Сценарий рекламного ролика для кофейни",
      model: "GPT-4o",
      status: "queued",
      progress: 0,
      credits: 6,
      createdAt: now - 90_000,
      updatedAt: now - 90_000,
    },
    {
      id: "task-4",
      type: "image",
      prompt: "Минималистичный логотип кофейни",
      model: "Flux",
      status: "done",
      progress: 100,
      credits: 80,
      durationSeconds: 12,
      createdAt: now - 600_000,
      updatedAt: now - 540_000,
    },
    {
      id: "task-5",
      type: "audio",
      prompt: "Озвучка приветствия мужским голосом",
      model: "ElevenLabs",
      status: "failed",
      progress: 42,
      credits: 25,
      error: "Недостаточно кредитов",
      createdAt: now - 300_000,
      updatedAt: now - 250_000,
    },
    {
      id: "task-6",
      type: "image",
      prompt: "Постер в стиле ретро-футуризм для выставки",
      model: "Seedream",
      status: "canceled",
      progress: 18,
      credits: 60,
      createdAt: now - 400_000,
      updatedAt: now - 350_000,
    },
    {
      id: "task-7",
      type: "text",
      prompt: "SEO-описание для лендинга SaaS-продукта",
      model: "Claude",
      status: "queued",
      progress: 0,
      credits: 4,
      createdAt: now - 60_000,
      updatedAt: now - 60_000,
    },
    {
      id: "task-8",
      type: "video",
      prompt: "Анимированный логотип с частицами",
      model: "Runway",
      status: "queued",
      progress: 0,
      credits: 200,
      createdAt: now - 30_000,
      updatedAt: now - 30_000,
    },
    {
      id: "task-9",
      type: "image",
      prompt: "Портрет кота в стиле масляной живописи",
      model: "Flux",
      status: "done",
      progress: 100,
      credits: 80,
      durationSeconds: 15,
      createdAt: now - 900_000,
      updatedAt: now - 850_000,
    },
    {
      id: "task-10",
      type: "audio",
      prompt: "Фоновая музыка для подкаста, lo-fi",
      model: "Suno",
      status: "done",
      progress: 100,
      credits: 40,
      durationSeconds: 45,
      createdAt: now - 1_200_000,
      updatedAt: now - 1_100_000,
    },
  ];
}
